name: schema-registry
lang: unknown
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  downstream_projects: ["kafka-rest", "ksql",
    "confluent-security-plugins", "kafka-connect-replicator",
    "ce-kafka-rest", "confluent-cloud-plugins", "schema-registry-plugins"]
git:
  enable: true
